export const viloyat = [
  {
    type_id: 1,
    id: 3,
    int01: 10,
    name1: "Andijon",
    name2: "Андижон",
    name3: "Андижанская область",
    name4: "Andijan",
  },
  {
    type_id: 1,
    id: 6,
    int01: 10,
    name1: "Buxoro",
    name2: "Бухоро",
    name3: "Бухарская область",
    name4: "Bukhara",
  },
  {
    type_id: 1,
    id: 30,
    int01: 10,
    name1: "Farg'ona",
    name2: "Фарғона",
    name3: "Ферганская область",
    name4: "Ferghana",
  },
  {
    type_id: 1,
    id: 8,
    int01: 10,
    name1: "Jizzax",
    name2: "Жиззах",
    name3: "Джиззакская область",
    name4: "Jizzakh",
  },
  {
    type_id: 1,
    id: 14,
    int01: 10,
    name1: "Namangan",
    name2: "Наманган",
    name3: "Наманганская область",
    name4: "Namangan",
  },
  {
    type_id: 1,
    id: 12,
    int01: 10,
    name1: "Navoiy",
    name2: "Навоий",
    name3: "Наваийская область",
    name4: "Navoi",
  },
  {
    type_id: 1,
    id: 10,
    int01: 10,
    name1: "Qashqadaryo",
    name2: "Қашқадарё",
    name3: "Кашкадаринская область",
    name4: "Kashkadarya",
  },
  {
    type_id: 1,
    id: 35,
    int01: 10,
    name1: "Qoraqalpog'iston Respublikasi",
    name2: "Қорақалпоғистон Республикаси",
    name3: "Республика Каракалпакстан",
    name4: "Republic of Karakalpakstan",
  },
  {
    type_id: 1,
    id: 18,
    int01: 10,
    name1: "Samarqand",
    name2: "Самарқанд",
    name3: "Самаркандская область",
    name4: "Samarkand",
  },
  {
    type_id: 1,
    id: 24,
    int01: 10,
    name1: "Sirdaryo",
    name2: "Сирдарё",
    name3: "Сирдаринская область",
    name4: "Sirdarya",
  },
  {
    type_id: 1,
    id: 22,
    int01: 10,
    name1: "Surxondaryo",
    name2: "Сурхондарё",
    name3: "Сурхондаринская область",
    name4: "Surkhandarya",
  },
  {
    type_id: 1,
    id: 27,
    int01: 10,
    name1: "Toshkent",
    name2: "Тошкент",
    name3: "Ташкентская область",
    name4: "Tashkent",
  },
  {
    type_id: 1,
    id: 26,
    int01: 10,
    name1: "Toshkent sh.",
    name2: "Тошкент ш.",
    name3: "город Ташкент",
    name4: "Tashkent sh.",
  },
  {
    type_id: 1,
    id: 33,
    int01: 10,
    name1: "Xorazm",
    name2: "Хоразм",
    name3: "Хорезмская область",
    name4: "Khorezm",
  },
];

export const tuman = [
  {
    type_id: 2,
    id: 3508,
    int01: 35,
    name1: "Amudaryo t.",
    name2: "Амударё т.",
    name3: "АМУДАРЬИНСКИЙ р-н",
    name4: "Amudarya district",
  },
  {
    type_id: 2,
    id: 301,
    int01: 3,
    name1: "Andijon sh.",
    name2: "Андижон ш.",
    name3: "г.АНДИЖАН",
    name4: "Andijan city",
  },
  {
    type_id: 2,
    id: 307,
    int01: 3,
    name1: "Andijon t.",
    name2: "Андижон т.",
    name3: "АНДИЖАНСКИЙ р-н",
    name4: "Andijan district",
  },
  {
    type_id: 2,
    id: 2203,
    int01: 22,
    name1: "Angor t.",
    name2: "Ангор т.",
    name3: "АНГОРСКИЙ р-н",
    name4: "Angor district",
  },
  {
    type_id: 2,
    id: 2716,
    int01: 27,
    name1: "Angren sh.",
    name2: "Ангрен ш.",
    name3: "г.АНГРЕН",
    name4: "Angren city",
  },
  {
    type_id: 2,
    id: 801,
    int01: 8,
    name1: "Arnasoy t.",
    name2: "Арнасой т.",
    name3: "АРНАСАЙСКИЙ р-н",
    name4: "Arnasoy district",
  },
  {
    type_id: 2,
    id: 315,
    int01: 3,
    name1: "Asaka t.",
    name2: "Асака т.",
    name3: "АСАКИНСКИЙ р-н",
    name4: "Asaka district",
  },
  {
    type_id: 2,
    id: 308,
    int01: 3,
    name1: "Baliqchi t.",
    name2: "Балиқчи т.",
    name3: "БАЛЫКЧИНСКИЙ р-н",
    name4: "Balikchi district",
  },
  {
    type_id: 2,
    id: 2216,
    int01: 22,
    name1: "Bandixon t.",
    name2: "Бандихон т.",
    name3: "БАНДИХОНСКИЙ р-н",
    name4: "Bandikhon district",
  },
  {
    type_id: 2,
    id: 802,
    int01: 8,
    name1: "Baxmal t.",
    name2: "Бахмал т.",
    name3: "БАХМАЛЬСКИЙ р-н",
    name4: "Bakhmal district",
  },
  {
    type_id: 2,
    id: 2402,
    int01: 24,
    name1: "Bayovut t.",
    name2: "Баёвут т.",
    name3: "БАЯУТСКИЙ р-н",
    name4: "Bayovut district",
  },
  {
    type_id: 2,
    id: 2717,
    int01: 27,
    name1: "Bekobod sh.",
    name2: "Бекобод ш.",
    name3: "г.БЕКАБАД",
    name4: "Bekobod city",
  },
  {
    type_id: 2,
    id: 2701,
    int01: 27,
    name1: "Bekobod t.",
    name2: "Бекобод т.",
    name3: "БЕКАБАДСКИЙ р-н",
    name4: "Bekobad district",
  },
  {
    type_id: 2,
    id: 2611,
    int01: 26,
    name1: "Bektemir t.",
    name2: "Бектемир т.",
    name3: "БЕКТЕМИРСКИЙ р-н",
    name4: "Bektemir district",
  },
  {
    type_id: 2,
    id: 3509,
    int01: 35,
    name1: "Beruniy t.",
    name2: "Беруний т.",
    name3: "БЕРУНИЙСКИЙ р-н",
    name4: "Beruni district",
  },
  {
    type_id: 2,
    id: 3006,
    int01: 30,
    name1: "Beshariq t.",
    name2: "Бешариқ т.",
    name3: "БЕШАРЫКСКИЙ р-н",
    name4: "Beshariq district",
  },
  {
    type_id: 2,
    id: 3007,
    int01: 30,
    name1: "Bog'dod t.",
    name2: "Боғдод т.",
    name3: "БАГДАДСКИЙ р-н",
    name4: "Baghdad district",
  },
  {
    type_id: 2,
    id: 3311,
    int01: 33,
    name1: "Bog'ot t.",
    name2: "Боғот т.",
    name3: "БАГАТСКИЙ р-н",
    name4: "Bogot district",
  },
  {
    type_id: 2,
    id: 2702,
    int01: 27,
    name1: "Bo'ka t.",
    name2: "Бўка т.",
    name3: "БУКИНСКИЙ р-н",
    name4: "Boka district",
  },
  {
    type_id: 2,
    id: 2703,
    int01: 27,
    name1: "Bo'stonlik t.",
    name2: "Бўстонлик т.",
    name3: "БОСТАНЛЫКСКИЙ р-н",
    name4: "Bostonlik district",
  },
  {
    type_id: 2,
    id: 2205,
    int01: 22,
    name1: "Boysun t.",
    name2: "Бойсун т.",
    name3: "БАЙСУНСКИЙ р-н",
    name4: "Boysun district",
  },
  {
    type_id: 2,
    id: 3510,
    int01: 35,
    name1: "Bo'zatov t.",
    name2: "Бўзатов т.",
    name3: "Бозатауский р-н",
    name4: "Bozatov district",
  },
  {
    type_id: 2,
    id: 309,
    int01: 3,
    name1: "Bo'z t.",
    name2: "Бўз т.",
    name3: "БОЗСКИЙ р-н",
    name4: "Boz district",
  },
  {
    type_id: 2,
    id: 310,
    int01: 3,
    name1: "Buloqboshi t.",
    name2: "Булоқбоши т.",
    name3: "БУЛАКБАШИНСКИЙ р-н",
    name4: "Bulakboshi district",
  },
  {
    type_id: 2,
    id: 1809,
    int01: 18,
    name1: "Bulung'ur t.",
    name2: "Булунғур т.",
    name3: "БУЛУНГУРСКИЙ р-н",
    name4: "Bulungur district",
  },
  {
    type_id: 2,
    id: 3008,
    int01: 30,
    name1: "Buvayda t.",
    name2: "Бувайда т.",
    name3: "БУВАЙДИНСКИЙ р-н",
    name4: "Buvayda district",
  },
  {
    type_id: 2,
    id: 601,
    int01: 6,
    name1: "Buxoro sh.",
    name2: "Бухоро ш.",
    name3: "г.БУХАРА",
    name4: "Bukhara city",
  },
  {
    type_id: 2,
    id: 605,
    int01: 6,
    name1: "Buxoro t.",
    name2: "Бухоро т.",
    name3: "БУХАРСКИЙ р-н",
    name4: "Bukhara district",
  },
  {
    type_id: 2,
    id: 2606,
    int01: 26,
    name1: "Chilonzor t.",
    name2: "Чилонзор т.",
    name3: "ЧИЛАНЗАРСКИЙ р-н",
    name4: "Chilonzor district",
  },
  {
    type_id: 2,
    id: 3519,
    int01: 35,
    name1: "Chimboy t.",
    name2: "Чимбой т.",
    name3: "ЧИМБАЙСКИЙ р-н",
    name4: "Chimboy district",
  },
  {
    type_id: 2,
    id: 2713,
    int01: 27,
    name1: "Chinoz t.",
    name2: "Чиноз т.",
    name3: "ЧИНАЗСКИЙ р-н",
    name4: "Chinoz district",
  },
  {
    type_id: 2,
    id: 2720,
    int01: 27,
    name1: "Chirchiq sh.",
    name2: "Чирчиқ ш.",
    name3: "г.ЧИРЧИК",
    name4: "Chirchik city",
  },
  {
    type_id: 2,
    id: 1014,
    int01: 10,
    name1: "Chiroqchi t.",
    name2: "Чироқчи т.",
    name3: "ЧИРАКЧИНСКИЙ р-н",
    name4: "Chirakchi district",
  },
  {
    type_id: 2,
    id: 1415,
    int01: 14,
    name1: "Chortoq t.",
    name2: "Чортоқ т.",
    name3: "ЧАРТАКСКИЙ р-н",
    name4: "Chortok district",
  },
  {
    type_id: 2,
    id: 1416,
    int01: 14,
    name1: "Chust t.",
    name2: "Чуст т.",
    name3: "ЧУСТСКИЙ р-н",
    name4: "Chust district",
  },
  {
    type_id: 2,
    id: 3009,
    int01: 30,
    name1: "Dang'ara t.",
    name2: "Данғара т.",
    name3: "ДАНГАРИНСКИЙ р-н",
    name4: "Dangara district",
  },
  {
    type_id: 2,
    id: 1418,
    int01: 14,
    name1: "Davlatobod t.",
    name2: "Давлатобод т.",
    name3: "ДАВЛАТОБОДСКИЙ р-н",
    name4: "Davlatabad district",
  },
  {
    type_id: 2,
    id: 2207,
    int01: 22,
    name1: "Denov t.",
    name2: "Денов т.",
    name3: "ДЕНАУССКИЙ р-н",
    name4: "Denov district",
  },
  {
    type_id: 2,
    id: 1005,
    int01: 10,
    name1: "Dexqonobod t.",
    name2: "Деҳқонобод т.",
    name3: "ДЕХКАНАБАДСКИЙ р-н",
    name4: "Dehkanabad district",
  },
  {
    type_id: 2,
    id: 805,
    int01: 8,
    name1: "Do'stlik t.",
    name2: "Дўстлик т.",
    name3: "ДУСТЛИКСКИЙ р-н",
    name4: "Friendship district",
  },
  {
    type_id: 2,
    id: 3521,
    int01: 35,
    name1: "Ellikqala t.",
    name2: "Элликқала т.",
    name3: "ЭЛЛИККАЛИНСКИЙ р-н",
    name4: "Ellikkala district",
  },
  {
    type_id: 2,
    id: 3005,
    int01: 30,
    name1: "Farg'ona sh.",
    name2: "Фарғона ш.",
    name3: "г.ФЕРГАНА",
    name4: "Fergana city",
  },
  {
    type_id: 2,
    id: 3019,
    int01: 30,
    name1: "Farg'ona t.",
    name2: "Фарғона т.",
    name3: "ФЕРГАНСКИЙ р-н",
    name4: "Fergana district",
  },
  {
    type_id: 2,
    id: 811,
    int01: 8,
    name1: "Forish t.",
    name2: "Фориш т.",
    name3: "ФАРИШСКИЙ р-н",
    name4: "Forish district",
  },
  {
    type_id: 2,
    id: 3020,
    int01: 30,
    name1: "Furqat t.",
    name2: "Фурқат т.",
    name3: "ФУРКАТСКИЙ р-н",
    name4: "Furqat district",
  },
  {
    type_id: 2,
    id: 803,
    int01: 8,
    name1: "G‘allaorol t.",
    name2: "Ғаллаорол т.",
    name3: "ГАЛЛЯАРАЛЬСКИЙ р-н",
    name4: "Gallaorol district",
  },
  {
    type_id: 2,
    id: 607,
    int01: 6,
    name1: "G'ijduvon t.",
    name2: "Ғиждувон т.",
    name3: "ГИЖДУВАНСКИЙ р-н",
    name4: "Gijduvan district",
  },
  {
    type_id: 2,
    id: 1213,
    int01: 12,
    name1: "Go'zg'on sh.",
    name2: "Ғозғон ш.",
    name3: "г.ГАЗГАН",
    name4: "Gozgon city",
  },
  {
    type_id: 2,
    id: 2410,
    int01: 24,
    name1: "Guliston sh.",
    name2: "Гулистон ш.",
    name3: "г.ГУЛИСТАН",
    name4: "Gulistan city",
  },
  {
    type_id: 2,
    id: 2403,
    int01: 24,
    name1: "Guliston t.",
    name2: "Гулистон т.",
    name3: "ГУЛИСТАНСКИЙ р-н",
    name4: "Gulistan district",
  },
  {
    type_id: 2,
    id: 3307,
    int01: 33,
    name1: "Gurlan t.",
    name2: "Гурлан т.",
    name3: "ГУРЛЕНСКИЙ р-н",
    name4: "Gurlan district",
  },
  {
    type_id: 2,
    id: 1004,
    int01: 10,
    name1: "G'uzor t.",
    name2: "Ғузор т.",
    name3: "ГУЗАРСКИЙ р-н",
    name4: "Guzor district",
  },
  {
    type_id: 2,
    id: 3306,
    int01: 33,
    name1: "Hazorasp t.",
    name2: "Ҳазорасп т.",
    name3: "ХАЗАРАСПСКИЙ р-н",
    name4: "Hazorasp district",
  },
  {
    type_id: 2,
    id: 1812,
    int01: 18,
    name1: "Ishtixon t.",
    name2: "Иштиҳон т.",
    name3: "ИШТЫХАНСКИЙ р-н",
    name4: "Istikhan district",
  },
  {
    type_id: 2,
    id: 312,
    int01: 3,
    name1: "Izboskan t.",
    name2: "Избоскан т.",
    name3: "ИЗБАСКАНСКИЙ р-н",
    name4: "Izboskan district",
  },
  {
    type_id: 2,
    id: 311,
    int01: 3,
    name1: "Jalaquduq t.",
    name2: "Жалақудуқ т.",
    name3: "ДЖАЛАЛКУДУКСКИЙ р-н",
    name4: "Jalakuduk district",
  },
  {
    type_id: 2,
    id: 2208,
    int01: 22,
    name1: "Jarqo'rg'on t.",
    name2: "Жарқўрғон т.",
    name3: "ДЖАРКУРГАНСКИЙ р-н",
    name4: "Jarkurgan district",
  },
  {
    type_id: 2,
    id: 812,
    int01: 8,
    name1: "Jizzax sh.",
    name2: "Жиззах ш.",
    name3: "г.ДЖИЗАК",
    name4: "Jizzakh city",
  },
  {
    type_id: 2,
    id: 1811,
    int01: 18,
    name1: "Jomboy t.",
    name2: "Жомбой т.",
    name3: "ДЖАМБАЙСКИЙ р-н",
    name4: "Jomboy district",
  },
  {
    type_id: 2,
    id: 608,
    int01: 6,
    name1: "Jondor t.",
    name2: "Жондор т.",
    name3: "ДЖАНДАРСКИЙ р-н",
    name4: "Jondor district",
  },
  {
    type_id: 2,
    id: 1211,
    int01: 12,
    name1: "Karmana t.",
    name2: "Кармана т.",
    name3: "КАРМАНИНСКИЙ р-н",
    name4: "Karmana district",
  },
  {
    type_id: 2,
    id: 1012,
    int01: 10,
    name1: "Kasbi t.",
    name2: "Касби т.",
    name3: "КАСБИНСКИЙ р-н",
    name4: "Kasby district",
  },
  {
    type_id: 2,
    id: 1806,
    int01: 18,
    name1: "Kattaqo'rg'on sh.",
    name2: "Каттақўрғон ш.",
    name3: "г.КАТТАКУРГАН",
    name4: "Kattakurgan city",
  },
  {
    type_id: 2,
    id: 1813,
    int01: 18,
    name1: "Kattaqo'rg'on t.",
    name2: "Каттақўрғон т.",
    name3: "КАТТАКУРГАНСКИЙ р-н",
    name4: "Kattakurgan district",
  },
  {
    type_id: 2,
    id: 3511,
    int01: 35,
    name1: "Kegeyli t.",
    name2: "Кегейли т.",
    name3: "КЕГЕЙЛИЙСКИЙ р-н",
    name4: "Kegeili district",
  },
  {
    type_id: 2,
    id: 1009,
    int01: 10,
    name1: "Kitob t.",
    name2: "Китоб т.",
    name3: "КИТАБСКИЙ р-н",
    name4: "Kitob district",
  },
  {
    type_id: 2,
    id: 603,
    int01: 6,
    name1: "Kogon sh.",
    name2: "Когон ш.",
    name3: "г.КАГАН",
    name4: "Kogon city",
  },
  {
    type_id: 2,
    id: 609,
    int01: 6,
    name1: "Kogon t.",
    name2: "Когон т.",
    name3: "КАГАНСКИЙ р-н",
    name4: "Kogon district",
  },
  {
    type_id: 2,
    id: 1018,
    int01: 10,
    name1: "Ko'kdala t.",
    name2: "Кўкдала т.",
    name3: "КЎКДАЛА Р-Н",
    name4: "Kokdala district",
  },
  {
    type_id: 2,
    id: 1204,
    int01: 12,
    name1: "Konimex t.",
    name2: "Конимех т.",
    name3: "КЕНИМЕХСКИЙ р-н",
    name4: "Konimex district",
  },
  {
    type_id: 2,
    id: 1408,
    int01: 14,
    name1: "Kosonsoy t.",
    name2: "Косонсой т.",
    name3: "КАСАНСАЙСКИЙ р-н",
    name4: "Kosonsoy district",
  },
  {
    type_id: 2,
    id: 1008,
    int01: 10,
    name1: "Koson t.",
    name2: "Косон т.",
    name3: "КАСАНСКИЙ р-н",
    name4: "Koson district",
  },
  {
    type_id: 2,
    id: 3004,
    int01: 30,
    name1: "Marg'ilon sh.",
    name2: "Марғилон ш.",
    name3: "г.МАРГИЛАН",
    name4: "Margilan city",
  },
  {
    type_id: 2,
    id: 316,
    int01: 3,
    name1: "Marhamat t.",
    name2: "Марҳамат т.",
    name3: "МАРХАМАТСКИЙ р-н",
    name4: "Thanks district",
  },
  {
    type_id: 2,
    id: 1407,
    int01: 14,
    name1: "Mingbuloq t.",
    name2: "Мингбулоқ т.",
    name3: "МИНГБУЛАКСКИЙ р-н",
    name4: "Mingbulok district",
  },
  {
    type_id: 2,
    id: 1017,
    int01: 10,
    name1: "Mirishkor t.",
    name2: "Миришкор т.",
    name3: "МИРИШКОРСКИЙ Р-Н",
    name4: "Mirishkor district",
  },
  {
    type_id: 2,
    id: 2601,
    int01: 26,
    name1: "Mirobod t.",
    name2: "Миробод т.",
    name3: "МИРАБАДСКИЙ р-н",
    name4: "Mirabad district",
  },
  {
    type_id: 2,
    id: 809,
    int01: 8,
    name1: "Mirzacho'l t.",
    name2: "Мирзачўл т.",
    name3: "МИРЗАЧУЛЬСКИЙ р-н",
    name4: "Mirzachol district",
  },
  {
    type_id: 2,
    id: 2405,
    int01: 24,
    name1: "Mirzaobod t.",
    name2: "Мирзаобод т.",
    name3: "МИРЗААБАДСКИЙ р-н",
    name4: "Mirzaabad district",
  },
  {
    type_id: 2,
    id: 3514,
    int01: 35,
    name1: "Mo'ynoq t.",
    name2: "Мўйноқ т.",
    name3: "МУЙНАКСКИЙ р-н",
    name4: "Moynok district",
  },
  {
    type_id: 2,
    id: 1010,
    int01: 10,
    name1: "Muborak t.",
    name2: "Муборак т.",
    name3: "МУБАРЕКСКИЙ р-н",
    name4: "Mubarak district",
  },
  {
    type_id: 2,
    id: 2602,
    int01: 26,
    name1: "M. Ulug'bek t.",
    name2: "М.Улугбек т.",
    name3: "МИРЗО-УЛУГБЕКСКИЙ р-н",
    name4: "M.Ulugbek district",
  },
  {
    type_id: 2,
    id: 2206,
    int01: 22,
    name1: "Muzrabod t.",
    name2: "Музрабод т.",
    name3: "МУЗРАБАДСКИЙ р-н",
    name4: "Muzrabod district",
  },
  {
    type_id: 2,
    id: 1401,
    int01: 14,
    name1: "Namangan sh.",
    name2: "Наманган ш.",
    name3: "г.НАМАНГАН",
    name4: "Namangan city",
  },
  {
    type_id: 2,
    id: 1409,
    int01: 14,
    name1: "Namangan t.",
    name2: "Наманган т.",
    name3: "НАМАНГАНСКИЙ р-н",
    name4: "Namangan district",
  },
  {
    type_id: 2,
    id: 1815,
    int01: 18,
    name1: "Narpay t.",
    name2: "Нарпай т.",
    name3: "НОРПАЙСКИЙ р-н",
    name4: "Narpay district",
  },
  {
    type_id: 2,
    id: 1208,
    int01: 12,
    name1: "Navbahor t.",
    name2: "Навбахор т.",
    name3: "НАВБАХОРСКИЙ р-н",
    name4: "Navbakhor district",
  },
  {
    type_id: 2,
    id: 1201,
    int01: 12,
    name1: "Navoiy sh.",
    name2: "Навоий ш.",
    name3: "г.НАВОИЙ",
    name4: "Navoi city",
  },
  {
    type_id: 2,
    id: 1011,
    int01: 10,
    name1: "Nishon t.",
    name2: "Нишон т.",
    name3: "НИШАНСКИЙ р-н",
    name4: "Target district",
  },
  {
    type_id: 2,
    id: 1410,
    int01: 14,
    name1: "Norin t.",
    name2: "Норин т.",
    name3: "НАРЫНСКИЙ р-н",
    name4: "Norin district",
  },
  {
    type_id: 2,
    id: 3501,
    int01: 35,
    name1: "Nukus sh.",
    name2: "Нукус ш.",
    name3: "г.НУКУС",
    name4: "Nukus city",
  },
  {
    type_id: 2,
    id: 3515,
    int01: 35,
    name1: "Nukus t.",
    name2: "Нукус т.",
    name3: "НУКУССКИЙ р-н",
    name4: "Nukus district",
  },
  {
    type_id: 2,
    id: 2723,
    int01: 27,
    name1: "Nurafshon sh.",
    name2: "Нурафшон ш.",
    name3: "город Нурафшон",
    name4: "Nurafshon city",
  },
  {
    type_id: 2,
    id: 1821,
    int01: 18,
    name1: "Nurobod t.",
    name2: "Нуробод т.",
    name3: "НУРОБАДСКИЙ р-н",
    name4: "Nurabad district",
  },
  {
    type_id: 2,
    id: 1210,
    int01: 12,
    name1: "Nurota t.",
    name2: "Нурота т.",
    name3: "НУРАТИНСКИЙ р-н",
    name4: "Nurota district",
  },
  {
    type_id: 2,
    id: 2711,
    int01: 27,
    name1: "Ohangaron sh.",
    name2: "Оҳангарон ш.",
    name3: "город Охангарон",
    name4: "Ahangaron city",
  },
  {
    type_id: 2,
    id: 2708,
    int01: 27,
    name1: "Ohangaron t.",
    name2: "Оҳангарон т.",
    name3: "АХАНГАРАНСКИЙ р-н",
    name4: "Ohangaron district",
  },
  {
    type_id: 2,
    id: 2718,
    int01: 27,
    name1: "Olmaliq sh.",
    name2: "Олмалиқ ш.",
    name3: "г.АЛМАЛЫК",
    name4: "Almalik city",
  },
  {
    type_id: 2,
    id: 2609,
    int01: 26,
    name1: "Olmazor t.",
    name2: "Олмазор т.",
    name3: "АЛМАЗАРСКИЙ р-н",
    name4: "Almazor district",
  },
  {
    type_id: 2,
    id: 604,
    int01: 6,
    name1: "Olot t.",
    name2: "Олот т.",
    name3: "АЛАТСКИЙ р-н",
    name4: "Olot district",
  },
  {
    type_id: 2,
    id: 3012,
    int01: 30,
    name1: "Oltiariq t.",
    name2: "Олтиариқ т.",
    name3: "АЛТЫАРЫКСКИЙ р-н",
    name4: "Altyariq district",
  },
  {
    type_id: 2,
    id: 306,
    int01: 3,
    name1: "Oltinko'l t.",
    name2: "Олтинкўл т.",
    name3: "АЛТЫНКУЛЬСКИЙ р-н",
    name4: "Oltinkol district",
  },
  {
    type_id: 2,
    id: 2204,
    int01: 22,
    name1: "Oltinsoy t.",
    name2: "Олтинсой т.",
    name3: "АЛТЫНСАЙСКИЙ р-н",
    name4: "Altinsoy district",
  },
  {
    type_id: 2,
    id: 1808,
    int01: 18,
    name1: "Oqdaryo t.",
    name2: "Оқдарё т.",
    name3: "АКДАРЬИНСКИЙ р-н",
    name4: "Akdaryo district",
  },
  {
    type_id: 2,
    id: 2401,
    int01: 24,
    name1: "Oqoltin t.",
    name2: "Оқолтин т.",
    name3: "ОКАЛТЫНСКИЙ р-н",
    name4: "Aqoltin district",
  },
  {
    type_id: 2,
    id: 2707,
    int01: 27,
    name1: "Oqqo'rg'on t.",
    name2: "Оққўрғон т.",
    name3: "АККУРГАНСКИЙ р-н",
    name4: "Akkorgon district",
  },
  {
    type_id: 2,
    id: 2712,
    int01: 27,
    name1: "O'rta-Chirchiq t.",
    name2: "Ўрта-чирчиқ т.",
    name3: "УРТА-ЧИРЧИКСКИЙ р-н",
    name4: "Average-Chirchik district",
  },
  {
    type_id: 2,
    id: 3017,
    int01: 30,
    name1: "O'zbekiston t.",
    name2: "Ўзбекистон т.",
    name3: "УЗБЕКИСТАНСКИЙ р-н",
    name4: "Uzbekistan district",
  },
  {
    type_id: 2,
    id: 2709,
    int01: 27,
    name1: "Parkent t.",
    name2: "Паркент т.",
    name3: "ПАРКЕНТСКИЙ р-н",
    name4: "Parkent district",
  },
  {
    type_id: 2,
    id: 1818,
    int01: 18,
    name1: "Pastdarg'om t.",
    name2: "Пастдарғом т.",
    name3: "ПАСТДАРГОМСКИЙ р-н",
    name4: "Pasdargom district",
  },
  {
    type_id: 2,
    id: 1819,
    int01: 18,
    name1: "Paxtachi t.",
    name2: "Пахтачи т.",
    name3: "ПАХТААЧИНСКИЙ р-н",
    name4: "Cotton district",
  },
  {
    type_id: 2,
    id: 810,
    int01: 8,
    name1: "Paxtakor t.",
    name2: "Пахтакор т.",
    name3: "ПАХТАКОРСКИЙ р-н",
    name4: "Pakhtakor district",
  },
  {
    type_id: 2,
    id: 318,
    int01: 3,
    name1: "Paxtaobod t.",
    name2: "Пахтаобод т.",
    name3: "ПАХТААБАДСКИЙ р-н",
    name4: "Pakhtaabad district",
  },
  {
    type_id: 2,
    id: 1817,
    int01: 18,
    name1: "Payariq t.",
    name2: "Пайариқ т.",
    name3: "ПАЙАРЫКСКИЙ р-н",
    name4: "Payarik district",
  },
  {
    type_id: 2,
    id: 611,
    int01: 6,
    name1: "Peshku t.",
    name2: "Пешку т.",
    name3: "ПЕШКУНСКИЙ р-н",
    name4: "Peshku district",
  },
  {
    type_id: 2,
    id: 2710,
    int01: 27,
    name1: "Piskent t.",
    name2: "Пискент т.",
    name3: "ПСКЕНТСКИЙ р-н",
    name4: "Piskent district",
  },
  {
    type_id: 2,
    id: 1411,
    int01: 14,
    name1: "Pop t.",
    name2: "Поп т.",
    name3: "ПАПСКИЙ р-н",
    name4: "Pop district",
  },
  {
    type_id: 2,
    id: 1006,
    int01: 10,
    name1: "Qamashi t.",
    name2: "Қамаши т.",
    name3: "КАМАШИНСКИЙ р-н",
    name4: "Qamashi district",
  },
  {
    type_id: 2,
    id: 1001,
    int01: 10,
    name1: "Qarshi sh.",
    name2: "Қарши ш.",
    name3: "г.КАРШИ",
    name4: "Karshi city",
  },
  {
    type_id: 2,
    id: 1007,
    int01: 10,
    name1: "Qarshi t.",
    name2: "Қарши т.",
    name3: "КАРШИНСКИЙ р-н",
    name4: "Karshi district",
  },
  {
    type_id: 2,
    id: 614,
    int01: 6,
    name1: "Q-bozor t.",
    name2: "Қ-бозор т.",
    name3: "КАРАУЛБАЗАРСКИЙ р-н",
    name4: "Q-bazar district",
  },
  {
    type_id: 2,
    id: 2706,
    int01: 27,
    name1: "Qibray t.",
    name2: "Қибрай т.",
    name3: "КИБРАЙСКИЙ р-н",
    name4: "Kibrai district",
  },
  {
    type_id: 2,
    id: 1205,
    int01: 12,
    name1: "Qiziltepa t.",
    name2: "Қизилтепа т.",
    name3: "КЫЗЫЛТЕПИНСКИЙ р-н",
    name4: "Kiziltepa district",
  },
  {
    type_id: 2,
    id: 2210,
    int01: 22,
    name1: "Qiziriq t.",
    name2: "Қизириқ т.",
    name3: "КИЗИРИКСКИЙ р-н",
    name4: "Interesting district",
  },
  {
    type_id: 2,
    id: 3512,
    int01: 35,
    name1: "Qo'ng'irot t.",
    name2: "Қўнғирот т.",
    name3: "КУНГРАДСКИЙ р-н",
    name4: "Kungrat district",
  },
  {
    type_id: 2,
    id: 3513,
    int01: 35,
    name1: "Qonliko'l t.",
    name2: "Қонликўл т.",
    name3: "КАНДИКУЛЬСКИЙ р-н",
    name4: "Konlikol district",
  },
  {
    type_id: 2,
    id: 610,
    int01: 6,
    name1: "Qorako'l t.",
    name2: "Қоракўл т.",
    name3: "КАРАКУЛЬСКИЙ р-н",
    name4: "Karakol district",
  },
  {
    type_id: 2,
    id: 3522,
    int01: 35,
    name1: "Qorao'zak t.",
    name2: "Қораўзак т.",
    name3: "КАРАУЗЯКСКИЙ р-н",
    name4: "Karakozak district",
  },
  {
    type_id: 2,
    id: 305,
    int01: 3,
    name1: "Qorasuv sh.",
    name2: "Қорасув ш.",
    name3: "г.КАРАСУ",
    name4: "Karasuv city",
  },
  {
    type_id: 2,
    id: 314,
    int01: 3,
    name1: "Qo'rg'ontepa t.",
    name2: "Қўрғонтепа т.",
    name3: "КУРГАНТЕПИНСКИЙ р-н",
    name4: "Korgontepa district",
  },
  {
    type_id: 2,
    id: 3310,
    int01: 33,
    name1: "Qo'shko'pir t.",
    name2: "Қўшкўпир т.",
    name3: "КУШКУПЫРСКИЙ р-н",
    name4: "Koshkopir district",
  },
  {
    type_id: 2,
    id: 1814,
    int01: 18,
    name1: "Qo'shrobod t.",
    name2: "Қўшрабод т.",
    name3: "КОШРАБАДСКИЙ р-н",
    name4: "Koshrabod district",
  },
  {
    type_id: 2,
    id: 3013,
    int01: 30,
    name1: "Qo'shtepa t.",
    name2: "Қўштепа т.",
    name3: "КУШТЕПИНСКИЙ р-н",
    name4: "Koshtepa district",
  },
  {
    type_id: 2,
    id: 2209,
    int01: 22,
    name1: "Qumqo'rg'on t.",
    name2: "Қумқўрғон т.",
    name3: "КУМКУРГАНСКИЙ р-н",
    name4: "Kumkurgan district",
  },
  {
    type_id: 2,
    id: 3003,
    int01: 30,
    name1: "Quqon sh.",
    name2: "Қуқон ш.",
    name3: "г.КОКАНД",
    name4: "Kukan city",
  },
  {
    type_id: 2,
    id: 3001,
    int01: 30,
    name1: "Quvasoy sh.",
    name2: "Қувасой ш.",
    name3: "г.КУВАСАЙ",
    name4: "Kuvasoy city",
  },
  {
    type_id: 2,
    id: 3011,
    int01: 30,
    name1: "Quva t.",
    name2: "Қува т.",
    name3: "КУВИНСКИЙ р-н",
    name4: "Kuva district",
  },
  {
    type_id: 2,
    id: 2714,
    int01: 27,
    name1: "Quyi-chirchiq t.",
    name2: "Қуйи-чирчиқ т.",
    name3: "КУЙИ-ЧИРЧИКСКИЙ р-н",
    name4: "Low-pitched district",
  },
  {
    type_id: 2,
    id: 3014,
    int01: 30,
    name1: "Rishton t.",
    name2: "Риштон т.",
    name3: "РИШТАНСКИЙ р-н",
    name4: "Rishton district",
  },
  {
    type_id: 2,
    id: 612,
    int01: 6,
    name1: "Romitan t.",
    name2: "Ромитан т.",
    name3: "РОМИТАНСКИЙ р-н",
    name4: "Romitan district",
  },
  {
    type_id: 2,
    id: 1801,
    int01: 18,
    name1: "Samarqand sh.",
    name2: "Самарқанд ш.",
    name3: "г.САМАРКАНД",
    name4: "Samarkand city",
  },
  {
    type_id: 2,
    id: 1820,
    int01: 18,
    name1: "Samarqand t.",
    name2: "Самарқанд т.",
    name3: "САМАРКАНДСКИЙ р-н",
    name4: "Samarkand district",
  },
  {
    type_id: 2,
    id: 2409,
    int01: 24,
    name1: "Sardoba t.",
    name2: "Сардоба т.",
    name3: "САРДОБИНСКИЙ р-н",
    name4: "Sardoba district",
  },
  {
    type_id: 2,
    id: 2211,
    int01: 22,
    name1: "Sariosiyo t.",
    name2: "Сариосиё т.",
    name3: "САРЫАССИЙСКИЙ р-н",
    name4: "Sariosya district",
  },
  {
    type_id: 2,
    id: 2406,
    int01: 24,
    name1: "Sayxunobod t.",
    name2: "Сайхунобод т.",
    name3: "САЙХУНАБАДСКИЙ р-н",
    name4: "Saykhunabad district",
  },
  {
    type_id: 2,
    id: 2607,
    int01: 26,
    name1: "Sergeli t.",
    name2: "Сергели т.",
    name3: "СЕРГЕЛИНСКИЙ р-н",
    name4: "Sergely district",
  },
  {
    type_id: 2,
    id: 1002,
    int01: 10,
    name1: "Shahrisabz sh.",
    name2: "Шахрисабз ш.",
    name3: "город ШАХРИЗАБСКИЙ ",
    name4: "Shahrisabz city",
  },
  {
    type_id: 2,
    id: 1015,
    int01: 10,
    name1: "Shahrisabz t.",
    name2: "Шахрисабз т.",
    name3: "ШАХРИЗАБСКИЙ р-н",
    name4: "Shahrisabz district",
  },
  {
    type_id: 2,
    id: 317,
    int01: 3,
    name1: "Shakrixon t.",
    name2: "Шаҳрихон т.",
    name3: "ШАХРИХАНСКИЙ р-н",
    name4: "Shahrikhan district",
  },
  {
    type_id: 2,
    id: 2605,
    int01: 26,
    name1: "Shayxontohur t.",
    name2: "Шайхонтохур т.",
    name3: "ШАЙХАНТАУРСКИЙ р-н",
    name4: "Shaikhontokhur district",
  },
  {
    type_id: 2,
    id: 2213,
    int01: 22,
    name1: "Sherobod t.",
    name2: "Шеробод т.",
    name3: "ШЕРАБАДСКИЙ р-н",
    name4: "Sherabad district",
  },
  {
    type_id: 2,
    id: 2412,
    int01: 24,
    name1: "Shirin sh.",
    name2: "Ширин ш.",
    name3: "г.ШИРИН",
    name4: "Shirin city",
  },
  {
    type_id: 2,
    id: 613,
    int01: 6,
    name1: "Shofirkon t.",
    name2: "Шофиркон т.",
    name3: "ШАФИРКАНСКИЙ р-н",
    name4: "Shafirkon district",
  },
  {
    type_id: 2,
    id: 2214,
    int01: 22,
    name1: "Sho'rchi t.",
    name2: "Шўрчи т.",
    name3: "ШУРЧИНСКИЙ р-н",
    name4: "Shorchi district",
  },
  {
    type_id: 2,
    id: 3308,
    int01: 33,
    name1: "Shovot t.",
    name2: "Шовот т.",
    name3: "ШАВАТСКИЙ р-н",
    name4: "Shavat district",
  },
  {
    type_id: 2,
    id: 804,
    int01: 8,
    name1: "Sh.Rashidov t.",
    name2: "Ш.Рашидов т.",
    name3: "ДЖИЗАКСКИЙ р-н",
    name4: "Sh. Rashidov district",
  },
  {
    type_id: 2,
    id: 3520,
    int01: 35,
    name1: "Shumanay t.",
    name2: "Шуманай т.",
    name3: "ШУМАНАЙСКИЙ р-н",
    name4: "Shumanai district",
  },
  {
    type_id: 2,
    id: 2407,
    int01: 24,
    name1: "Sirdaryo t.",
    name2: "Сирдарё т.",
    name3: "СЫРДАРЬИНСКИЙ р-н",
    name4: "Sirdarya district",
  },
  {
    type_id: 2,
    id: 3015,
    int01: 30,
    name1: "So'x t.",
    name2: "Сўх т.",
    name3: "СОХСКИЙ р-н",
    name4: "Sokh district",
  },
  {
    type_id: 2,
    id: 3504,
    int01: 35,
    name1: "Taxiatosh t.",
    name2: "Тахиатош т.",
    name3: "ТАХИАТАШСКИЙ р-н",
    name4: "Takhiatosh district",
  },
  {
    type_id: 2,
    id: 3516,
    int01: 35,
    name1: "Taxtako'pir t.",
    name2: "Тахтакўпир т.",
    name3: "ТАХТАКУПЫРСКИЙ р-н",
    name4: "Takhtakopir district",
  },
  {
    type_id: 2,
    id: 2201,
    int01: 22,
    name1: "Termiz sh.",
    name2: "Термиз ш.",
    name3: "г.ТЕРМЕЗ",
    name4: "Termiz city",
  },
  {
    type_id: 2,
    id: 2212,
    int01: 22,
    name1: "Termiz t.",
    name2: "Термиз т.",
    name3: "ТЕРМЕЗСКИЙ р-н",
    name4: "Termiz district",
  },
  {
    type_id: 2,
    id: 1207,
    int01: 12,
    name1: "Tomdi t.",
    name2: "Томди т.",
    name3: "ТАМДЫНСКИЙ р-н",
    name4: "Tomdi district",
  },
  {
    type_id: 2,
    id: 1412,
    int01: 14,
    name1: "To'raqo'rg'on t.",
    name2: "Тўрақўрғон т.",
    name3: "ТУРАКУРГАНСКИЙ р-н",
    name4: "Toragorgon district",
  },
  {
    type_id: 2,
    id: 3517,
    int01: 35,
    name1: "To'rtko'l t.",
    name2: "Тўрткўл т.",
    name3: "ТУРТКУЛЬСКИЙ р-н",
    name4: "Tortkol district",
  },
  {
    type_id: 2,
    id: 2722,
    int01: 27,
    name1: "Toshkent t.",
    name2: "Тошкент т.",
    name3: "Ташкентский район",
    name4: "Tashkent city",
  },
  {
    type_id: 2,
    id: 3016,
    int01: 30,
    name1: "Toshloq t.",
    name2: "Тошлоқ т.",
    name3: "ТАШЛАКСКИЙ р-н",
    name4: "Tashlok district",
  },
  {
    type_id: 2,
    id: 1804,
    int01: 18,
    name1: "Toyloq t.",
    name2: "Тойлоқ т.",
    name3: "ТАЙЛЯКСКИЙ р-н",
    name4: "Toiloq district",
  },
  {
    type_id: 2,
    id: 3314,
    int01: 33,
    name1: "Tuproqqal'a t.",
    name2: "Тупроққалъа т.",
    name3: "ТУПРАККАЛИНСКИЙ р-н",
    name4: "Tuproqkala district",
  },
  {
    type_id: 2,
    id: 3018,
    int01: 30,
    name1: "Uchko'prik t.",
    name2: "Учкўприк т.",
    name3: "УЧКУПРИКСКИЙ р-н",
    name4: "Uchkoprik district",
  },
  {
    type_id: 2,
    id: 1414,
    int01: 14,
    name1: "Uchqo'rg'on t.",
    name2: "Учқўрғон т.",
    name3: "УЧКУРГАНСКИЙ р-н",
    name4: "Uchkurgan district",
  },
  {
    type_id: 2,
    id: 1203,
    int01: 12,
    name1: "Uchquduq sh.",
    name2: "Учқудуқ ш.",
    name3: "г.УЧКУДУК",
    name4: "Uchkuduk city",
  },
  {
    type_id: 2,
    id: 2610,
    int01: 26,
    name1: "Uchtepa t.",
    name2: "Учтепа т.",
    name3: "УЧТЕПИНСКИЙ РАЙОН",
    name4: "Uchtep district",
  },
  {
    type_id: 2,
    id: 313,
    int01: 3,
    name1: "Ulug'nor t.",
    name2: "Улуғнор т.",
    name3: "УЛУГНОРСКИЙ р-н",
    name4: "Ulugnor district",
  },
  {
    type_id: 2,
    id: 3301,
    int01: 33,
    name1: "Urganch sh.",
    name2: "Урганч ш.",
    name3: "г.УРГЕНЧ",
    name4: "Urganch city",
  },
  {
    type_id: 2,
    id: 3304,
    int01: 33,
    name1: "Urganch t.",
    name2: "Урганч т.",
    name3: "УРГЕНЧСКИЙ р-н",
    name4: "Urganch district",
  },
  {
    type_id: 2,
    id: 1822,
    int01: 18,
    name1: "Urgut t.",
    name2: "Ургут т.",
    name3: "УРГУТССКИЙ р-н",
    name4: "Urgut district",
  },
  {
    type_id: 2,
    id: 1413,
    int01: 14,
    name1: "Uychi t.",
    name2: "Уйчи т.",
    name3: "УЙЧИНСКИЙ р-н",
    name4: "Uychi district",
  },
  {
    type_id: 2,
    id: 2215,
    int01: 22,
    name1: "Uzun t.",
    name2: "Узун т.",
    name3: "УЗУНСКИЙ р-н",
    name4: "Uzun district",
  },
  {
    type_id: 2,
    id: 606,
    int01: 6,
    name1: "Vobkent t.",
    name2: "Вобкент т.",
    name3: "ВАБКЕНТСКИЙ р-н",
    name4: "Vobkent district",
  },
  {
    type_id: 2,
    id: 1209,
    int01: 12,
    name1: "Xatirchi t.",
    name2: "Хатирчи т.",
    name3: "ХАТЫРЧИНСКИЙ р-н",
    name4: "Khatirchi district",
  },
  {
    type_id: 2,
    id: 3303,
    int01: 33,
    name1: "Xiva sh.",
    name2: "Хива ш.",
    name3: "г.ДРУЖБА",
    name4: "Khiva city",
  },
  {
    type_id: 2,
    id: 3305,
    int01: 33,
    name1: "Xiva t.",
    name2: "Хива т.",
    name3: "ХИВИНСКИЙ р-н",
    name4: "Khiva district",
  },
  {
    type_id: 2,
    id: 3518,
    int01: 35,
    name1: "Xojali t.",
    name2: "Хўжайли т.",
    name3: "ХОДЖЕЙЛИЙСКИЙ р-н",
    name4: "Khojaly district",
  },
  {
    type_id: 2,
    id: 319,
    int01: 3,
    name1: "Xo'jaobod t.",
    name2: "Хўжаобод т.",
    name3: "ХОДЖААБАДСКИЙ р-н",
    name4: "Khojaabad district",
  },
  {
    type_id: 2,
    id: 303,
    int01: 3,
    name1: "Xonobod sh.",
    name2: "Хонобод ш.",
    name3: "г.ХАНАБАД",
    name4: "Khanabad city",
  },
  {
    type_id: 2,
    id: 3312,
    int01: 33,
    name1: "Xonqa t.",
    name2: "Хонқа т.",
    name3: "ХАНКИНСКИЙ р-н",
    name4: "Khanka district",
  },
  {
    type_id: 2,
    id: 2408,
    int01: 24,
    name1: "Xovos t.",
    name2: "Ховос т.",
    name3: "ХАВАСТСКИЙ р-н",
    name4: "Havos district",
  },
  {
    type_id: 2,
    id: 1016,
    int01: 10,
    name1: "Yakkabog' t.",
    name2: "Яккабоғ т.",
    name3: "ЯККАБАГСКИЙ р-н",
    name4: "Yakkabak district",
  },
  {
    type_id: 2,
    id: 2604,
    int01: 26,
    name1: "Yakkasaroy t.",
    name2: "Яккасарой т.",
    name3: "ЯККАСАРАЙСКИЙ р-н",
    name4: "Yakkasaroy district",
  },
  {
    type_id: 2,
    id: 3309,
    int01: 33,
    name1: "Yangiariq t.",
    name2: "Янгиариқ т.",
    name3: "ЯНГИАРЫКСКИЙ р-н",
    name4: "Yangariq district",
  },
  {
    type_id: 2,
    id: 3313,
    int01: 33,
    name1: "Yangibozor t.",
    name2: "Янгибозор т.",
    name3: "ЯНГИБАЗАРСКИЙ р-н",
    name4: "Yangibozor district",
  },
  {
    type_id: 2,
    id: 2612,
    int01: 26,
    name1: "Yangihayot t.",
    name2: "Янгиҳаёт т.",
    name3: "ЯНГИХАЙОТСКИЙ р-н",
    name4: "Yangihayat district",
  },
  {
    type_id: 2,
    id: 1419,
    int01: 14,
    name1: "Yangi Namangan t.",
    name2: "Янги Наманган т.",
    name3: "Новый Наманган р-н",
    name4: "New Namangan district",
  },
  {
    type_id: 2,
    id: 813,
    int01: 8,
    name1: "Yangiobod t.",
    name2: "Янгиобод т.",
    name3: "ЯНГИАБАДСКИЙ р-н",
    name4: "Yangiabad district",
  },
  {
    type_id: 2,
    id: 1417,
    int01: 14,
    name1: "Yangiqo'rg'on t.",
    name2: "Янгиқўрғон т.",
    name3: "ЯНГИКУРГАНСКИЙ р-н",
    name4: "Yangikurgan district",
  },
  {
    type_id: 2,
    id: 2413,
    int01: 24,
    name1: "Yangiyer sh.",
    name2: "Янгиер ш.",
    name3: "г.ЯНГИЕР",
    name4: "Yangier city",
  },
  {
    type_id: 2,
    id: 2721,
    int01: 27,
    name1: "Yangiyo'l sh.",
    name2: "Янгийўл ш.",
    name3: "город Янгийўл",
    name4: "Yangyol city",
  },
  {
    type_id: 2,
    id: 2715,
    int01: 27,
    name1: "Yangiyo'l t.",
    name2: "Янгийўл т.",
    name3: "ЯНГИЙУЛЬСКИЙ р-н",
    name4: "Yangyol district",
  },
  {
    type_id: 2,
    id: 2608,
    int01: 26,
    name1: "Yashnobod t.",
    name2: "Яшнобод т.",
    name3: "ХАМЗИНСКИЙ р-н",
    name4: "Yashnabad district",
  },
  {
    type_id: 2,
    id: 3010,
    int01: 30,
    name1: "Yozyovon t.",
    name2: "Ёзёвон т.",
    name3: "ЯЗЬЯВАНСКИЙ р-н",
    name4: "Yozyovon district",
  },
  {
    type_id: 2,
    id: 2603,
    int01: 26,
    name1: "Yunusobod t.",
    name2: "Юнусобод т.",
    name3: "ЮНУСАБАДСКИЙ р-н",
    name4: "Yunusabad district",
  },
  {
    type_id: 2,
    id: 2705,
    int01: 27,
    name1: "Yuqori-chirchiq t.",
    name2: "Юқори-чирчиқ т.",
    name3: "ЮКОРИ-ЧИРЧИКСКИЙ р-н",
    name4: "High-Chirchik district",
  },
  {
    type_id: 2,
    id: 808,
    int01: 8,
    name1: "Zafarobod t.",
    name2: "Зафаробод т.",
    name3: "ЗАФАРАБАДСКИЙ р-н",
    name4: "Zafarabad district",
  },
  {
    type_id: 2,
    id: 2704,
    int01: 27,
    name1: "Zangiota t.",
    name2: "Зангиота т.",
    name3: "ЗАНГИАТИНСКИЙ р-н",
    name4: "Zangiota district",
  },
  {
    type_id: 2,
    id: 1202,
    int01: 12,
    name1: "Zarafshon sh.",
    name2: "Зарафшон ш.",
    name3: "г.ЗАРАВШАН",
    name4: "Zarafshon city",
  },
  {
    type_id: 2,
    id: 806,
    int01: 8,
    name1: "Zarbdor t.",
    name2: "Зарбдор т.",
    name3: "ЗАРБДОРСКИЙ р-н",
    name4: "Zarbdar district",
  },
  {
    type_id: 2,
    id: 807,
    int01: 8,
    name1: "Zomin t.",
    name2: "Зомин т.",
    name3: "ЗААМИНСКИЙ р-н",
    name4: "Zomin district",
  },
];
