export const viloyat = [
  {
    number: 13,
    name1: "Qoraqalpog'iston Respublikasi",
    name2: "Қорақалпоғистон Республикаси",
    name3: "Республика Каракалпакстан",
    name4: "Republic of Karakalpakstan",
  },
  {
    number: 2,
    name1: "Andijon",
    name2: "Андижон",
    name3: "Андижанская область",
    name4: "Andijan",
  },
  {
    number: 3,
    name1: "Buxoro",
    name2: "Бухоро",
    name3: "Бухарская область",
    name4: "Bukhara",
  },
  {
    number: 4,
    name1: "Jizzax",
    name2: "Жиззах",
    name3: "Джиззакская область",
    name4: "Jizzakh",
  },
  {
    number: 5,
    name1: "Qashqadaryo",
    name2: "Қашқадарё",
    name3: "Кашкадаринская область",
    name4: "Kashkadarya",
  },
  {
    number: 6,
    name1: "Navoiy",
    name2: "Навоий",
    name3: "Наваийская область",
    name4: "Navoi",
  },
  {
    number: 7,
    name1: "Namangan",
    name2: "Наманган",
    name3: "Наманганская область",
    name4: "Namangan",
  },
  {
    number: 8,
    name1: "Samarqand",
    name2: "Самарқанд",
    name3: "Самаркандская область",
    name4: "Samarkand",
  },
  {
    number: 9,
    name1: "Surxondaryo",
    name2: "Сурхондарё",
    name3: "Сурхондаринская область",
    name4: "Surkhandarya",
  },
  {
    number: 10,
    name1: "Sirdaryo",
    name2: "Сирдарё",
    name3: "Сирдаринская область",
    name4: "Sirdarya",
  },
  {
    number: 11,
    name1: "Toshkent",
    name2: "Тошкент",
    name3: "Ташкентская область",
    name4: "Tashkent",
  },
  {
    number: 12,
    name1: "Farg'ona",
    name2: "Фарғона",
    name3: "Ферганская область",
    name4: "Ferghana",
  },
  {
    number: 1,
    name1: "Xorazm",
    name2: "Хоразм",
    name3: "Хорезмская область",
    name4: "Khorezm",
  },
  {
    number: 14,
    name1: "Toshkent sh.",
    name2: "Тошкент ш.",
    name3: "город Ташкент",
    name4: "Tashkent sh.",
  },
];

export const tuman = [
  {
    number: 101,
    name1: "Urganch sh.",
    name2: "Урганч ш.",
    name3: "г.УРГЕНЧ",
    name4: "Urganch city",
    parent_number: 1,
  },
  {
    number: 103,
    name1: "Xiva sh.",
    name2: "Хива ш.",
    name3: "г.ДРУЖБА",
    name4: "Khiva city",
    parent_number: 1,
  },
  {
    number: 104,
    name1: "Urganch t.",
    name2: "Урганч т.",
    name3: "УРГЕНЧСКИЙ р-н",
    name4: "Urganch district",
    parent_number: 1,
  },
  {
    number: 105,
    name1: "Xiva t.",
    name2: "Хива т.",
    name3: "ХИВИНСКИЙ р-н",
    name4: "Khiva district",
    parent_number: 1,
  },
  {
    number: 106,
    name1: "Hazorasp t.",
    name2: "Ҳазорасп т.",
    name3: "ХАЗАРАСПСКИЙ р-н",
    name4: "Hazorasp district",
    parent_number: 1,
  },
  {
    number: 107,
    name1: "Gurlan t.",
    name2: "Гурлан т.",
    name3: "ГУРЛЕНСКИЙ р-н",
    name4: "Gurlan district",
    parent_number: 1,
  },
  {
    number: 108,
    name1: "Shovot t.",
    name2: "Шовот т.",
    name3: "ШАВАТСКИЙ р-н",
    name4: "Shavat district",
    parent_number: 1,
  },
  {
    number: 109,
    name1: "Yangiariq t.",
    name2: "Янгиариқ т.",
    name3: "ЯНГИАРЫКСКИЙ р-н",
    name4: "Yangariq district",
    parent_number: 1,
  },
  {
    number: 110,
    name1: "Qo'shko'pir t.",
    name2: "Қўшкўпир т.",
    name3: "КУШКУПЫРСКИЙ р-н",
    name4: "Koshkopir district",
    parent_number: 1,
  },
  {
    number: 111,
    name1: "Bog'ot t.",
    name2: "Боғот т.",
    name3: "БАГАТСКИЙ р-н",
    name4: "Bogot district",
    parent_number: 1,
  },
  {
    number: 112,
    name1: "Xonqa t.",
    name2: "Хонқа т.",
    name3: "ХАНКИНСКИЙ р-н",
    name4: "Khanka district",
    parent_number: 1,
  },
  {
    number: 113,
    name1: "Yangibozor t.",
    name2: "Янгибозор т.",
    name3: "ЯНГИБАЗАРСКИЙ р-н",
    name4: "Yangibozor district",
    parent_number: 1,
  },
  {
    number: 114,
    name1: "Tuproqqal'a t.",
    name2: "Тупроққалъа т.",
    name3: "ТУПРАККАЛИНСКИЙ р-н",
    name4: "Tuproqkala district",
    parent_number: 1,
  },
  {
    number: 201,
    name1: "Andijon sh.",
    name2: "Андижон ш.",
    name3: "г.АНДИЖАН",
    name4: "Andijan city",
    parent_number: 2,
  },
  {
    number: 203,
    name1: "Xonobod sh.",
    name2: "Хонобод ш.",
    name3: "г.ХАНАБАД",
    name4: "Khanabad city",
    parent_number: 2,
  },
  {
    number: 205,
    name1: "Qorasuv sh.",
    name2: "Қорасув ш.",
    name3: "г.КАРАСУ",
    name4: "Karasuv city",
    parent_number: 2,
  },
  {
    number: 206,
    name1: "Oltinko'l t.",
    name2: "Олтинкўл т.",
    name3: "АЛТЫНКУЛЬСКИЙ р-н",
    name4: "Oltinkol district",
    parent_number: 2,
  },
  {
    number: 207,
    name1: "Andijon t.",
    name2: "Андижон т.",
    name3: "АНДИЖАНСКИЙ р-н",
    name4: "Andijan district",
    parent_number: 2,
  },
  {
    number: 208,
    name1: "Baliqchi t.",
    name2: "Балиқчи т.",
    name3: "БАЛЫКЧИНСКИЙ р-н",
    name4: "Balikchi district",
    parent_number: 2,
  },
  {
    number: 209,
    name1: "Bo'z t.",
    name2: "Бўз т.",
    name3: "БОЗСКИЙ р-н",
    name4: "Boz district",
    parent_number: 2,
  },
  {
    number: 210,
    name1: "Buloqboshi t.",
    name2: "Булоқбоши т.",
    name3: "БУЛАКБАШИНСКИЙ р-н",
    name4: "Bulakboshi district",
    parent_number: 2,
  },
  {
    number: 211,
    name1: "Jalaquduq t.",
    name2: "Жалақудуқ т.",
    name3: "ДЖАЛАЛКУДУКСКИЙ р-н",
    name4: "Jalakuduk district",
    parent_number: 2,
  },
  {
    number: 212,
    name1: "Izboskan t.",
    name2: "Избоскан т.",
    name3: "ИЗБАСКАНСКИЙ р-н",
    name4: "Izboskan district",
    parent_number: 2,
  },
  {
    number: 213,
    name1: "Ulug'nor t.",
    name2: "Улуғнор т.",
    name3: "УЛУГНОРСКИЙ р-н",
    name4: "Ulugnor district",
    parent_number: 2,
  },
  {
    number: 214,
    name1: "Qo'rg'ontepa t.",
    name2: "Қўрғонтепа т.",
    name3: "КУРГАНТЕПИНСКИЙ р-н",
    name4: "Korgontepa district",
    parent_number: 2,
  },
  {
    number: 215,
    name1: "Asaka t.",
    name2: "Асака т.",
    name3: "АСАКИНСКИЙ р-н",
    name4: "Asaka district",
    parent_number: 2,
  },
  {
    number: 216,
    name1: "Marhamat t.",
    name2: "Марҳамат т.",
    name3: "МАРХАМАТСКИЙ р-н",
    name4: "Thanks district",
    parent_number: 2,
  },
  {
    number: 217,
    name1: "Shakrixon t.",
    name2: "Шаҳрихон т.",
    name3: "ШАХРИХАНСКИЙ р-н",
    name4: "Shahrikhan district",
    parent_number: 2,
  },
  {
    number: 218,
    name1: "Paxtaobod t.",
    name2: "Пахтаобод т.",
    name3: "ПАХТААБАДСКИЙ р-н",
    name4: "Pakhtaabad district",
    parent_number: 2,
  },
  {
    number: 219,
    name1: "Xo'jaobod t.",
    name2: "Хўжаобод т.",
    name3: "ХОДЖААБАДСКИЙ р-н",
    name4: "Khojaabad district",
    parent_number: 2,
  },
  {
    number: 301,
    name1: "Buxoro sh.",
    name2: "Бухоро ш.",
    name3: "г.БУХАРА",
    name4: "Bukhara city",
    parent_number: 3,
  },
  {
    number: 303,
    name1: "Kogon sh.",
    name2: "Когон ш.",
    name3: "г.КАГАН",
    name4: "Kogon city",
    parent_number: 3,
  },
  {
    number: 304,
    name1: "Olot t.",
    name2: "Олот т.",
    name3: "АЛАТСКИЙ р-н",
    name4: "Olot district",
    parent_number: 3,
  },
  {
    number: 305,
    name1: "Buxoro t.",
    name2: "Бухоро т.",
    name3: "БУХАРСКИЙ р-н",
    name4: "Bukhara district",
    parent_number: 3,
  },
  {
    number: 306,
    name1: "Vobkent t.",
    name2: "Вобкент т.",
    name3: "ВАБКЕНТСКИЙ р-н",
    name4: "Vobkent district",
    parent_number: 3,
  },
  {
    number: 307,
    name1: "G'ijduvon t.",
    name2: "Ғиждувон т.",
    name3: "ГИЖДУВАНСКИЙ р-н",
    name4: "Gijduvan district",
    parent_number: 3,
  },
  {
    number: 308,
    name1: "Jondor t.",
    name2: "Жондор т.",
    name3: "ДЖАНДАРСКИЙ р-н",
    name4: "Jondor district",
    parent_number: 3,
  },
  {
    number: 309,
    name1: "Kogon t.",
    name2: "Когон т.",
    name3: "КАГАНСКИЙ р-н",
    name4: "Kogon district",
    parent_number: 3,
  },
  {
    number: 310,
    name1: "Qorako'l t.",
    name2: "Қоракўл т.",
    name3: "КАРАКУЛЬСКИЙ р-н",
    name4: "Karakol district",
    parent_number: 3,
  },
  {
    number: 311,
    name1: "Peshku t.",
    name2: "Пешку т.",
    name3: "ПЕШКУНСКИЙ р-н",
    name4: "Peshku district",
    parent_number: 3,
  },
  {
    number: 312,
    name1: "Romitan t.",
    name2: "Ромитан т.",
    name3: "РОМИТАНСКИЙ р-н",
    name4: "Romitan district",
    parent_number: 3,
  },
  {
    number: 313,
    name1: "Shofirkon t.",
    name2: "Шофиркон т.",
    name3: "ШАФИРКАНСКИЙ р-н",
    name4: "Shafirkon district",
    parent_number: 3,
  },
  {
    number: 314,
    name1: "Q-bozor t.",
    name2: "Қ-бозор т.",
    name3: "КАРАУЛБАЗАРСКИЙ р-н",
    name4: "Q-bazar district",
    parent_number: 3,
  },
  {
    number: 401,
    name1: "Arnasoy t.",
    name2: "Арнасой т.",
    name3: "АРНАСАЙСКИЙ р-н",
    name4: "Arnasoy district",
    parent_number: 4,
  },
  {
    number: 402,
    name1: "Baxmal t.",
    name2: "Бахмал т.",
    name3: "БАХМАЛЬСКИЙ р-н",
    name4: "Bakhmal district",
    parent_number: 4,
  },
  {
    number: 403,
    name1: "G‘allaorol t.",
    name2: "Ғаллаорол т.",
    name3: "ГАЛЛЯАРАЛЬСКИЙ р-н",
    name4: "Gallaorol district",
    parent_number: 4,
  },
  {
    number: 404,
    name1: "Sh.Rashidov t.",
    name2: "Ш.Рашидов т.",
    name3: "ДЖИЗАКСКИЙ р-н",
    name4: "Sh. Rashidov district",
    parent_number: 4,
  },
  {
    number: 405,
    name1: "Do'stlik t.",
    name2: "Дўстлик т.",
    name3: "ДУСТЛИКСКИЙ р-н",
    name4: "Friendship district",
    parent_number: 4,
  },
  {
    number: 406,
    name1: "Zarbdor t.",
    name2: "Зарбдор т.",
    name3: "ЗАРБДОРСКИЙ р-н",
    name4: "Zarbdar district",
    parent_number: 4,
  },
  {
    number: 407,
    name1: "Zomin t.",
    name2: "Зомин т.",
    name3: "ЗААМИНСКИЙ р-н",
    name4: "Zomin district",
    parent_number: 4,
  },
  {
    number: 408,
    name1: "Zafarobod t.",
    name2: "Зафаробод т.",
    name3: "ЗАФАРАБАДСКИЙ р-н",
    name4: "Zafarabad district",
    parent_number: 4,
  },
  {
    number: 409,
    name1: "Mirzacho'l t.",
    name2: "Мирзачўл т.",
    name3: "МИРЗАЧУЛЬСКИЙ р-н",
    name4: "Mirzachol district",
    parent_number: 4,
  },
  {
    number: 410,
    name1: "Paxtakor t.",
    name2: "Пахтакор т.",
    name3: "ПАХТАКОРСКИЙ р-н",
    name4: "Pakhtakor district",
    parent_number: 4,
  },
  {
    number: 411,
    name1: "Forish t.",
    name2: "Фориш т.",
    name3: "ФАРИШСКИЙ р-н",
    name4: "Forish district",
    parent_number: 4,
  },
  {
    number: 412,
    name1: "Jizzax sh.",
    name2: "Жиззах ш.",
    name3: "г.ДЖИЗАК",
    name4: "Jizzakh city",
    parent_number: 4,
  },
  {
    number: 413,
    name1: "Yangiobod t.",
    name2: "Янгиобод т.",
    name3: "ЯНГИАБАДСКИЙ р-н",
    name4: "Yangiabad district",
    parent_number: 4,
  },
  {
    number: 501,
    name1: "Qarshi sh.",
    name2: "Қарши ш.",
    name3: "г.КАРШИ",
    name4: "Karshi city",
    parent_number: 5,
  },
  {
    number: 502,
    name1: "Shahrisabz sh.",
    name2: "Шахрисабз ш.",
    name3: "город ШАХРИЗАБСКИЙ ",
    name4: "Shahrisabz city",
    parent_number: 5,
  },
  {
    number: 504,
    name1: "G'uzor t.",
    name2: "Ғузор т.",
    name3: "ГУЗАРСКИЙ р-н",
    name4: "Guzor district",
    parent_number: 5,
  },
  {
    number: 505,
    name1: "Dexqonobod t.",
    name2: "Деҳқонобод т.",
    name3: "ДЕХКАНАБАДСКИЙ р-н",
    name4: "Dehkanabad district",
    parent_number: 5,
  },
  {
    number: 506,
    name1: "Qamashi t.",
    name2: "Қамаши т.",
    name3: "КАМАШИНСКИЙ р-н",
    name4: "Qamashi district",
    parent_number: 5,
  },
  {
    number: 507,
    name1: "Qarshi t.",
    name2: "Қарши т.",
    name3: "КАРШИНСКИЙ р-н",
    name4: "Karshi district",
    parent_number: 5,
  },
  {
    number: 508,
    name1: "Koson t.",
    name2: "Косон т.",
    name3: "КАСАНСКИЙ р-н",
    name4: "Koson district",
    parent_number: 5,
  },
  {
    number: 509,
    name1: "Kitob t.",
    name2: "Китоб т.",
    name3: "КИТАБСКИЙ р-н",
    name4: "Kitob district",
    parent_number: 5,
  },
  {
    number: 510,
    name1: "Muborak t.",
    name2: "Муборак т.",
    name3: "МУБАРЕКСКИЙ р-н",
    name4: "Mubarak district",
    parent_number: 5,
  },
  {
    number: 511,
    name1: "Nishon t.",
    name2: "Нишон т.",
    name3: "НИШАНСКИЙ р-н",
    name4: "Target district",
    parent_number: 5,
  },
  {
    number: 512,
    name1: "Kasbi t.",
    name2: "Касби т.",
    name3: "КАСБИНСКИЙ р-н",
    name4: "Kasby district",
    parent_number: 5,
  },
  {
    number: 514,
    name1: "Chiroqchi t.",
    name2: "Чироқчи т.",
    name3: "ЧИРАКЧИНСКИЙ р-н",
    name4: "Chirakchi district",
    parent_number: 5,
  },
  {
    number: 515,
    name1: "Shahrisabz t.",
    name2: "Шахрисабз т.",
    name3: "ШАХРИЗАБСКИЙ р-н",
    name4: "Shahrisabz district",
    parent_number: 5,
  },
  {
    number: 516,
    name1: "Yakkabog' t.",
    name2: "Яккабоғ т.",
    name3: "ЯККАБАГСКИЙ р-н",
    name4: "Yakkabak district",
    parent_number: 5,
  },
  {
    number: 517,
    name1: "Mirishkor t.",
    name2: "Миришкор т.",
    name3: "МИРИШКОРСКИЙ Р-Н",
    name4: "Mirishkor district",
    parent_number: 5,
  },
  {
    number: 518,
    name1: "Ko'kdala t.",
    name2: "Кўкдала т.",
    name3: "КЎКДАЛА Р-Н",
    name4: "Kokdala district",
    parent_number: 5,
  },
  {
    number: 601,
    name1: "Navoiy sh.",
    name2: "Навоий ш.",
    name3: "г.НАВОИЙ",
    name4: "Navoi city",
    parent_number: 6,
  },
  {
    number: 602,
    name1: "Zarafshon sh.",
    name2: "Зарафшон ш.",
    name3: "г.ЗАРАВШАН",
    name4: "Zarafshon city",
    parent_number: 6,
  },
  {
    number: 603,
    name1: "Uchquduq sh.",
    name2: "Учқудуқ ш.",
    name3: "г.УЧКУДУК",
    name4: "Uchkuduk city",
    parent_number: 6,
  },
  {
    number: 604,
    name1: "Konimex t.",
    name2: "Конимех т.",
    name3: "КЕНИМЕХСКИЙ р-н",
    name4: "Konimex district",
    parent_number: 6,
  },
  {
    number: 605,
    name1: "Qiziltepa t.",
    name2: "Қизилтепа т.",
    name3: "КЫЗЫЛТЕПИНСКИЙ р-н",
    name4: "Kiziltepa district",
    parent_number: 6,
  },
  {
    number: 607,
    name1: "Tomdi t.",
    name2: "Томди т.",
    name3: "ТАМДЫНСКИЙ р-н",
    name4: "Tomdi district",
    parent_number: 6,
  },
  {
    number: 608,
    name1: "Navbahor t.",
    name2: "Навбахор т.",
    name3: "НАВБАХОРСКИЙ р-н",
    name4: "Navbakhor district",
    parent_number: 6,
  },
  {
    number: 609,
    name1: "Xatirchi t.",
    name2: "Хатирчи т.",
    name3: "ХАТЫРЧИНСКИЙ р-н",
    name4: "Khatirchi district",
    parent_number: 6,
  },
  {
    number: 610,
    name1: "Nurota t.",
    name2: "Нурота т.",
    name3: "НУРАТИНСКИЙ р-н",
    name4: "Nurota district",
    parent_number: 6,
  },
  {
    number: 611,
    name1: "Karmana t.",
    name2: "Кармана т.",
    name3: "КАРМАНИНСКИЙ р-н",
    name4: "Karmana district",
    parent_number: 6,
  },
  {
    number: 613,
    name1: "Go'zg'on sh.",
    name2: "Ғозғон ш.",
    name3: "г.ГАЗГАН",
    name4: "Gozgon city",
    parent_number: 6,
  },
  {
    number: 701,
    name1: "Namangan sh.",
    name2: "Наманган ш.",
    name3: "г.НАМАНГАН",
    name4: "Namangan city",
    parent_number: 7,
  },
  {
    number: 707,
    name1: "Mingbuloq t.",
    name2: "Мингбулоқ т.",
    name3: "МИНГБУЛАКСКИЙ р-н",
    name4: "Mingbulok district",
    parent_number: 7,
  },
  {
    number: 708,
    name1: "Kosonsoy t.",
    name2: "Косонсой т.",
    name3: "КАСАНСАЙСКИЙ р-н",
    name4: "Kosonsoy district",
    parent_number: 7,
  },
  {
    number: 709,
    name1: "Namangan t.",
    name2: "Наманган т.",
    name3: "НАМАНГАНСКИЙ р-н",
    name4: "Namangan district",
    parent_number: 7,
  },
  {
    number: 710,
    name1: "Norin t.",
    name2: "Норин т.",
    name3: "НАРЫНСКИЙ р-н",
    name4: "Norin district",
    parent_number: 7,
  },
  {
    number: 711,
    name1: "Pop t.",
    name2: "Поп т.",
    name3: "ПАПСКИЙ р-н",
    name4: "Pop district",
    parent_number: 7,
  },
  {
    number: 712,
    name1: "To'raqo'rg'on t.",
    name2: "Тўрақўрғон т.",
    name3: "ТУРАКУРГАНСКИЙ р-н",
    name4: "Toragorgon district",
    parent_number: 7,
  },
  {
    number: 713,
    name1: "Uychi t.",
    name2: "Уйчи т.",
    name3: "УЙЧИНСКИЙ р-н",
    name4: "Uychi district",
    parent_number: 7,
  },
  {
    number: 714,
    name1: "Uchqo'rg'on t.",
    name2: "Учқўрғон т.",
    name3: "УЧКУРГАНСКИЙ р-н",
    name4: "Uchkurgan district",
    parent_number: 7,
  },
  {
    number: 715,
    name1: "Chortoq t.",
    name2: "Чортоқ т.",
    name3: "ЧАРТАКСКИЙ р-н",
    name4: "Chortok district",
    parent_number: 7,
  },
  {
    number: 716,
    name1: "Chust t.",
    name2: "Чуст т.",
    name3: "ЧУСТСКИЙ р-н",
    name4: "Chust district",
    parent_number: 7,
  },
  {
    number: 717,
    name1: "Yangiqo'rg'on t.",
    name2: "Янгиқўрғон т.",
    name3: "ЯНГИКУРГАНСКИЙ р-н",
    name4: "Yangikurgan district",
    parent_number: 7,
  },
  {
    number: 718,
    name1: "Davlatobod t.",
    name2: "Давлатобод т.",
    name3: "ДАВЛАТОБОДСКИЙ р-н",
    name4: "Davlatabad district",
    parent_number: 7,
  },
  {
    number: 719,
    name1: "Yangi Namangan t.",
    name2: "Янги Наманган т.",
    name3: "Новый Наманган р-н",
    name4: "New Namangan district",
    parent_number: 7,
  },
  {
    number: 801,
    name1: "Samarqand sh.",
    name2: "Самарқанд ш.",
    name3: "г.САМАРКАНД",
    name4: "Samarkand city",
    parent_number: 8,
  },
  {
    number: 804,
    name1: "Toyloq t.",
    name2: "Тойлоқ т.",
    name3: "ТАЙЛЯКСКИЙ р-н",
    name4: "Toiloq district",
    parent_number: 8,
  },
  {
    number: 806,
    name1: "Kattaqo'rg'on sh.",
    name2: "Каттақўрғон ш.",
    name3: "г.КАТТАКУРГАН",
    name4: "Kattakurgancity",
    parent_number: 8,
  },
  {
    number: 808,
    name1: "Oqdaryo t.",
    name2: "Оқдарё т.",
    name3: "АКДАРЬИНСКИЙ р-н",
    name4: "Akdaryo district",
    parent_number: 8,
  },
  {
    number: 809,
    name1: "Bulung'ur t.",
    name2: "Булунғур т.",
    name3: "БУЛУНГУРСКИЙ р-н",
    name4: "Bulungur district",
    parent_number: 8,
  },
  {
    number: 811,
    name1: "Jomboy t.",
    name2: "Жомбой т.",
    name3: "ДЖАМБАЙСКИЙ р-н",
    name4: "Jomboy district",
    parent_number: 8,
  },
  {
    number: 812,
    name1: "Ishtixon t.",
    name2: "Иштиҳон т.",
    name3: "ИШТЫХАНСКИЙ р-н",
    name4: "Istikhan district",
    parent_number: 8,
  },
  {
    number: 813,
    name1: "Kattaqo'rg'on t.",
    name2: "Каттақўрғон т.",
    name3: "КАТТАКУРГАНСКИЙ р-н",
    name4: "Kattakurgan district",
    parent_number: 8,
  },
  {
    number: 814,
    name1: "Qo'shrobod t.",
    name2: "Қўшрабод т.",
    name3: "КОШРАБАДСКИЙ р-н",
    name4: "Koshrabod distrit",
    parent_number: 8,
  },
  {
    number: 815,
    name1: "Narpay t.",
    name2: "Нарпай т.",
    name3: "НОРПАЙСКИЙ р-н",
    name4: "Narpay district",
    parent_number: 8,
  },
  {
    number: 817,
    name1: "Payariq t.",
    name2: "Пайариқ т.",
    name3: "ПАЙАРЫКСКИЙ р-н",
    name4: "Payarik district",
    parent_number: 8,
  },
  {
    number: 818,
    name1: "Pastdarg'om t.",
    name2: "Пастдарғом т.",
    name3: "ПАСТДАРГОМСКИЙ р-н",
    name4: "Pasdargom district",
    parent_number: 8,
  },
  {
    number: 819,
    name1: "Paxtachi t.",
    name2: "Пахтачи т.",
    name3: "ПАХТААЧИНСКИЙ р-н",
    name4: "Cotton district",
    parent_number: 8,
  },
  {
    number: 820,
    name1: "Samarqand t.",
    name2: "Самарқанд т.",
    name3: "САМАРКАНДСКИЙ р-н",
    name4: "Samarkand district",
    parent_number: 8,
  },
  {
    number: 821,
    name1: "Nurobod t.",
    name2: "Нуробод т.",
    name3: "НУРОБАДСКИЙ р-н",
    name4: "Nurabad district",
    parent_number: 8,
  },
  {
    number: 822,
    name1: "Urgut t.",
    name2: "Ургут т.",
    name3: "УРГУТССКИЙ р-н",
    name4: "Urgut district",
    parent_number: 8,
  },
  {
    number: 901,
    name1: "Termiz sh.",
    name2: "Термиз ш.",
    name3: "г.ТЕРМЕЗ",
    name4: "Termiz city",
    parent_number: 9,
  },
  {
    number: 903,
    name1: "Angor t.",
    name2: "Ангор т.",
    name3: "АНГОРСКИЙ р-н",
    name4: "Angor district",
    parent_number: 9,
  },
  {
    number: 904,
    name1: "Oltinsoy t.",
    name2: "Олтинсой т.",
    name3: "АЛТЫНСАЙСКИЙ р-н",
    name4: "Altinsoy district",
    parent_number: 9,
  },
  {
    number: 905,
    name1: "Boysun t.",
    name2: "Бойсун т.",
    name3: "БАЙСУНСКИЙ р-н",
    name4: "Boysun district",
    parent_number: 9,
  },
  {
    number: 906,
    name1: "Muzrabod t.",
    name2: "Музрабод т.",
    name3: "МУЗРАБАДСКИЙ р-н",
    name4: "Muzrabod district",
    parent_number: 9,
  },
  {
    number: 907,
    name1: "Denov t.",
    name2: "Денов т.",
    name3: "ДЕНАУССКИЙ р-н",
    name4: "Denov district",
    parent_number: 9,
  },
  {
    number: 908,
    name1: "Jarqo'rg'on t.",
    name2: "Жарқўрғон т.",
    name3: "ДЖАРКУРГАНСКИЙ р-н",
    name4: "Jarkurgan district",
    parent_number: 9,
  },
  {
    number: 909,
    name1: "Qumqo'rg'on t.",
    name2: "Қумқўрғон т.",
    name3: "КУМКУРГАНСКИЙ р-н",
    name4: "Kumkurgan district",
    parent_number: 9,
  },
  {
    number: 910,
    name1: "Qiziriq t.",
    name2: "Қизириқ т.",
    name3: "КИЗИРИКСКИЙ р-н",
    name4: "Interesting district",
    parent_number: 9,
  },
  {
    number: 911,
    name1: "Sariosiyo t.",
    name2: "Сариосиё т.",
    name3: "САРЫАССИЙСКИЙ р-н",
    name4: "Sariosya district",
    parent_number: 9,
  },
  {
    number: 912,
    name1: "Termiz t.",
    name2: "Термиз т.",
    name3: "ТЕРМЕЗСКИЙ р-н",
    name4: "Termiz district",
    parent_number: 9,
  },
  {
    number: 913,
    name1: "Sherobod t.",
    name2: "Шеробод т.",
    name3: "ШЕРАБАДСКИЙ р-н",
    name4: "Sherabad district",
    parent_number: 9,
  },
  {
    number: 914,
    name1: "Sho'rchi t.",
    name2: "Шўрчи т.",
    name3: "ШУРЧИНСКИЙ р-н",
    name4: "Shorchi district",
    parent_number: 9,
  },
  {
    number: 915,
    name1: "Uzun t.",
    name2: "Узун т.",
    name3: "УЗУНСКИЙ р-н",
    name4: "Uzun district",
    parent_number: 9,
  },
  {
    number: 916,
    name1: "Bandixon t.",
    name2: "Бандихон т.",
    name3: "БАНДИХОНСКИЙ р-н",
    name4: "Bandikhon district",
    parent_number: 9,
  },
  {
    number: 1001,
    name1: "Oqoltin t.",
    name2: "Оқолтин т.",
    name3: "ОКАЛТЫНСКИЙ р-н",
    name4: "Aqoltin district",
    parent_number: 10,
  },
  {
    number: 1002,
    name1: "Bayovut t.",
    name2: "Баёвут т.",
    name3: "БАЯУТСКИЙ р-н",
    name4: "Bayovut district",
    parent_number: 10,
  },
  {
    number: 1003,
    name1: "Guliston t.",
    name2: "Гулистон т.",
    name3: "ГУЛИСТАНСКИЙ р-н",
    name4: "Gulistan district",
    parent_number: 10,
  },
  {
    number: 1005,
    name1: "Mirzaobod t.",
    name2: "Мирзаобод т.",
    name3: "МИРЗААБАДСКИЙ р-н",
    name4: "Mirzaabad district",
    parent_number: 10,
  },
  {
    number: 1006,
    name1: "Sayxunobod t.",
    name2: "Сайхунобод т.",
    name3: "САЙХУНАБАДСКИЙ р-н",
    name4: "Saykhunabad district",
    parent_number: 10,
  },
  {
    number: 1007,
    name1: "Sirdaryo t.",
    name2: "Сирдарё т.",
    name3: "СЫРДАРЬИНСКИЙ р-н",
    name4: "Sirdarya district",
    parent_number: 10,
  },
  {
    number: 1008,
    name1: "Xovos t.",
    name2: "Ховос т.",
    name3: "ХАВАСТСКИЙ р-н",
    name4: "Havos district",
    parent_number: 10,
  },
  {
    number: 1009,
    name1: "Sardoba t.",
    name2: "Сардоба т.",
    name3: "САРДОБИНСКИЙ р-н",
    name4: "Sardoba district",
    parent_number: 10,
  },
  {
    number: 1010,
    name1: "Guliston sh.",
    name2: "Гулистон ш.",
    name3: "г.ГУЛИСТАН",
    name4: "Gulistan city",
    parent_number: 10,
  },
  {
    number: 1012,
    name1: "Shirin sh.",
    name2: "Ширин ш.",
    name3: "г.ШИРИН",
    name4: "Shirin city",
    parent_number: 10,
  },
  {
    number: 1013,
    name1: "Yangiyer sh.",
    name2: "Янгиер ш.",
    name3: "г.ЯНГИЕР",
    name4: "Yangier city",
    parent_number: 10,
  },
  {
    number: 1101,
    name1: "Bekobod t.",
    name2: "Бекобод т.",
    name3: "БЕКАБАДСКИЙ р-н",
    name4: "Bekobad district",
    parent_number: 11,
  },
  {
    number: 1102,
    name1: "Bo'ka t.",
    name2: "Бўка т.",
    name3: "БУКИНСКИЙ р-н",
    name4: "Boka district",
    parent_number: 11,
  },
  {
    number: 1103,
    name1: "Bo'stonlik t.",
    name2: "Бўстонлик т.",
    name3: "БОСТАНЛЫКСКИЙ р-н",
    name4: "Bostonlik district",
    parent_number: 11,
  },
  {
    number: 1104,
    name1: "Zangiota t.",
    name2: "Зангиота т.",
    name3: "ЗАНГИАТИНСКИЙ р-н",
    name4: "Zangiota district",
    parent_number: 11,
  },
  {
    number: 1105,
    name1: "Yuqori-chirchiq t.",
    name2: "Юқори-чирчиқ т.",
    name3: "ЮКОРИ-ЧИРЧИКСКИЙ р-н",
    name4: "High-Chirchik district",
    parent_number: 11,
  },
  {
    number: 1106,
    name1: "Qibray t.",
    name2: "Қибрай т.",
    name3: "КИБРАЙСКИЙ р-н",
    name4: "Kibrai district",
    parent_number: 11,
  },
  {
    number: 1107,
    name1: "Oqqo'rg'on t.",
    name2: "Оққўрғон т.",
    name3: "АККУРГАНСКИЙ р-н",
    name4: "Akkorgon district",
    parent_number: 11,
  },
  {
    number: 1108,
    name1: "Ohangaron t.",
    name2: "Оҳангарон т.",
    name3: "АХАНГАРАНСКИЙ р-н",
    name4: "Ohangaron district",
    parent_number: 11,
  },
  {
    number: 1109,
    name1: "Parkent t.",
    name2: "Паркент т.",
    name3: "ПАРКЕНТСКИЙ р-н",
    name4: "Parkent district",
    parent_number: 11,
  },
  {
    number: 1110,
    name1: "Piskent t.",
    name2: "Пискент т.",
    name3: "ПСКЕНТСКИЙ р-н",
    name4: "Piskent district",
    parent_number: 11,
  },
  {
    number: 1111,
    name1: "Ohangaron sh.",
    name2: "Оҳангарон ш.",
    name3: "город Охангарон",
    name4: "Ahangaron city",
    parent_number: 11,
  },
  {
    number: 1112,
    name1: "O'rta-Chirchiq t.",
    name2: "Ўрта-чирчиқ т.",
    name3: "УРТА-ЧИРЧИКСКИЙ р-н",
    name4: "Average-Chirchik district",
    parent_number: 11,
  },
  {
    number: 1113,
    name1: "Chinoz t.",
    name2: "Чиноз т.",
    name3: "ЧИНАЗСКИЙ р-н",
    name4: "Chinoz district",
    parent_number: 11,
  },
  {
    number: 1114,
    name1: "Quyi-chirchiq t.",
    name2: "Қуйи-чирчиқ т.",
    name3: "КУЙИ-ЧИРЧИКСКИЙ р-н",
    name4: "Low-pitched district",
    parent_number: 11,
  },
  {
    number: 1115,
    name1: "Yangiyo'l t.",
    name2: "Янгийўл т.",
    name3: "ЯНГИЙУЛЬСКИЙ р-н",
    name4: "Yangyol district",
    parent_number: 11,
  },
  {
    number: 1116,
    name1: "Angren sh.",
    name2: "Ангрен ш.",
    name3: "г.АНГРЕН",
    name4: "Angren city",
    parent_number: 11,
  },
  {
    number: 1117,
    name1: "Bekobod sh.",
    name2: "Бекобод ш.",
    name3: "г.БЕКАБАД",
    name4: "Bekobod city",
    parent_number: 11,
  },
  {
    number: 1118,
    name1: "Olmaliq sh.",
    name2: "Олмалиқ ш.",
    name3: "г.АЛМАЛЫК",
    name4: "Almalik city",
    parent_number: 11,
  },
  {
    number: 1120,
    name1: "Chirchiq sh.",
    name2: "Чирчиқ ш.",
    name3: "г.ЧИРЧИК",
    name4: "Chirchik city",
    parent_number: 11,
  },
  {
    number: 1121,
    name1: "Yangiyo'l sh.",
    name2: "Янгийўл ш.",
    name3: "город Янгийўл",
    name4: "Yangyol city",
    parent_number: 11,
  },
  {
    number: 1122,
    name1: "Toshkent t.",
    name2: "Тошкент т.",
    name3: "Ташкентский район",
    name4: "Tashkent city",
    parent_number: 11,
  },
  {
    number: 1123,
    name1: "Nurafshon sh.",
    name2: "Нурафшон ш.",
    name3: "город Нурафшон",
    name4: "Nurafshon city",
    parent_number: 11,
  },
  {
    number: 1201,
    name1: "Quvasoy sh.",
    name2: "Қувасой ш.",
    name3: "г.КУВАСАЙ",
    name4: "Kuvasoy city",
    parent_number: 12,
  },
  {
    number: 1203,
    name1: "Quqon sh.",
    name2: "Қуқон ш.",
    name3: "г.КОКАНД",
    name4: "Kukan city",
    parent_number: 12,
  },
  {
    number: 1204,
    name1: "Marg'ilon sh.",
    name2: "Марғилон ш.",
    name3: "г.МАРГИЛАН",
    name4: "Margilan city",
    parent_number: 12,
  },
  {
    number: 1205,
    name1: "Farg'ona sh.",
    name2: "Фарғона ш.",
    name3: "г.ФЕРГАНА",
    name4: "Fergana city",
    parent_number: 12,
  },
  {
    number: 1206,
    name1: "Beshariq t.",
    name2: "Бешариқ т.",
    name3: "БЕШАРЫКСКИЙ р-н",
    name4: "Beshariq district",
    parent_number: 12,
  },
  {
    number: 1207,
    name1: "Bog'dod t.",
    name2: "Боғдод т.",
    name3: "БАГДАДСКИЙ р-н",
    name4: "Baghdad district",
    parent_number: 12,
  },
  {
    number: 1208,
    name1: "Buvayda t.",
    name2: "Бувайда т.",
    name3: "БУВАЙДИНСКИЙ р-н",
    name4: "Buvayda district",
    parent_number: 12,
  },
  {
    number: 1209,
    name1: "Dang'ara t.",
    name2: "Данғара т.",
    name3: "ДАНГАРИНСКИЙ р-н",
    name4: "Dangara district",
    parent_number: 12,
  },
  {
    number: 1210,
    name1: "Yozyovon t.",
    name2: "Ёзёвон т.",
    name3: "ЯЗЬЯВАНСКИЙ р-н",
    name4: "Yozyovon district",
    parent_number: 12,
  },
  {
    number: 1211,
    name1: "Quva t.",
    name2: "Қува т.",
    name3: "КУВИНСКИЙ р-н",
    name4: "Kuva district",
    parent_number: 12,
  },
  {
    number: 1212,
    name1: "Oltiariq t.",
    name2: "Олтиариқ т.",
    name3: "АЛТЫАРЫКСКИЙ р-н",
    name4: "Altyariq district",
    parent_number: 12,
  },
  {
    number: 1213,
    name1: "Qo'shtepa t.",
    name2: "Қўштепа т.",
    name3: "КУШТЕПИНСКИЙ р-н",
    name4: "Koshtepa district",
    parent_number: 12,
  },
  {
    number: 1214,
    name1: "Rishton t.",
    name2: "Риштон т.",
    name3: "РИШТАНСКИЙ р-н",
    name4: "Rishton district",
    parent_number: 12,
  },
  {
    number: 1215,
    name1: "So'x t.",
    name2: "Сўх т.",
    name3: "СОХСКИЙ р-н",
    name4: "Sokh district",
    parent_number: 12,
  },
  {
    number: 1216,
    name1: "Toshloq t.",
    name2: "Тошлоқ т.",
    name3: "ТАШЛАКСКИЙ р-н",
    name4: "Tashlok district",
    parent_number: 12,
  },
  {
    number: 1217,
    name1: "O'zbekiston t.",
    name2: "Ўзбекистон т.",
    name3: "УЗБЕКИСТАНСКИЙ р-н",
    name4: "Uzbekistan district",
    parent_number: 12,
  },
  {
    number: 1218,
    name1: "Uchko'prik t.",
    name2: "Учкўприк т.",
    name3: "УЧКУПРИКСКИЙ р-н",
    name4: "Uchkoprik district",
    parent_number: 12,
  },
  {
    number: 1219,
    name1: "Farg'ona t.",
    name2: "Фарғона т.",
    name3: "ФЕРГАНСКИЙ р-н",
    name4: "Fergana district",
    parent_number: 12,
  },
  {
    number: 1220,
    name1: "Furqat t.",
    name2: "Фурқат т.",
    name3: "ФУРКАТСКИЙ р-н",
    name4: "Furqat district",
    parent_number: 12,
  },
  {
    number: 1301,
    name1: "Nukus sh.",
    name2: "Нукус ш.",
    name3: "г.НУКУС",
    name4: "Nukus city",
    parent_number: 13,
  },
  {
    number: 1304,
    name1: "Taxiatosh t.",
    name2: "Тахиатош т.",
    name3: "ТАХИАТАШСКИЙ р-н",
    name4: "Takhiatosh district",
    parent_number: 13,
  },
  {
    number: 1308,
    name1: "Amudaryo t.",
    name2: "Амударё т.",
    name3: "АМУДАРЬИНСКИЙ р-н",
    name4: "Amudarya district",
    parent_number: 13,
  },
  {
    number: 1309,
    name1: "Beruniy t.",
    name2: "Беруний т.",
    name3: "БЕРУНИЙСКИЙ р-н",
    name4: "Beruni district",
    parent_number: 13,
  },
  {
    number: 1310,
    name1: "Bo'zatov t.",
    name2: "Бўзатов т.",
    name3: "Бозатауский р-н",
    name4: "Bozatov district",
    parent_number: 13,
  },
  {
    number: 1311,
    name1: "Kegeyli t.",
    name2: "Кегейли т.",
    name3: "КЕГЕЙЛИЙСКИЙ р-н",
    name4: "Kegeili district",
    parent_number: 13,
  },
  {
    number: 1312,
    name1: "Qo'ng'irot t.",
    name2: "Қўнғирот т.",
    name3: "КУНГРАДСКИЙ р-н",
    name4: "Kungrat district",
    parent_number: 13,
  },
  {
    number: 1313,
    name1: "Qonliko'l t.",
    name2: "Қонликўл т.",
    name3: "КАНДИКУЛЬСКИЙ р-н",
    name4: "Konlikol district",
    parent_number: 13,
  },
  {
    number: 1314,
    name1: "Mo'ynoq t.",
    name2: "Мўйноқ т.",
    name3: "МУЙНАКСКИЙ р-н",
    name4: "Moynok district",
    parent_number: 13,
  },
  {
    number: 1315,
    name1: "Nukus t.",
    name2: "Нукус т.",
    name3: "НУКУССКИЙ р-н",
    name4: "Nukus district",
    parent_number: 13,
  },
  {
    number: 1316,
    name1: "Taxtako'pir t.",
    name2: "Тахтакўпир т.",
    name3: "ТАХТАКУПЫРСКИЙ р-н",
    name4: "Takhtakopir district",
    parent_number: 13,
  },
  {
    number: 1317,
    name1: "To'rtko'l t.",
    name2: "Тўрткўл т.",
    name3: "ТУРТКУЛЬСКИЙ р-н",
    name4: "Tortkol district",
    parent_number: 13,
  },
  {
    number: 1318,
    name1: "Xojali t.",
    name2: "Хўжайли т.",
    name3: "ХОДЖЕЙЛИЙСКИЙ р-н",
    name4: "Khojaly district",
    parent_number: 13,
  },
  {
    number: 1319,
    name1: "Chimboy t.",
    name2: "Чимбой т.",
    name3: "ЧИМБАЙСКИЙ р-н",
    name4: "Chimboy district",
    parent_number: 13,
  },
  {
    number: 1320,
    name1: "Shumanay t.",
    name2: "Шуманай т.",
    name3: "ШУМАНАЙСКИЙ р-н",
    name4: "Shumanai district",
    parent_number: 13,
  },
  {
    number: 1321,
    name1: "Ellikqala t.",
    name2: "Элликқала т.",
    name3: "ЭЛЛИККАЛИНСКИЙ р-н",
    name4: "Ellikkala district",
    parent_number: 13,
  },
  {
    number: 1322,
    name1: "Qorao'zak t.",
    name2: "Қораўзак т.",
    name3: "КАРАУЗЯКСКИЙ р-н",
    name4: "Karakozak district",
    parent_number: 13,
  },
  {
    number: 1401,
    name1: "Mirobod t.",
    name2: "Миробод т.",
    name3: "МИРАБАДСКИЙ р-н",
    name4: "Mirabad district",
    parent_number: 14,
  },
  {
    number: 1402,
    name1: "M. Ulug'bek t.",
    name2: "М.Улугбек т.",
    name3: "МИРЗО-УЛУГБЕКСКИЙ р-н",
    name4: "M.Ulugbek district",
    parent_number: 14,
  },
  {
    number: 1403,
    name1: "Yunusobod t.",
    name2: "Юнусобод т.",
    name3: "ЮНУСАБАДСКИЙ р-н",
    name4: "Yunusabad district",
    parent_number: 14,
  },
  {
    number: 1404,
    name1: "Yakkasaroy t.",
    name2: "Яккасарой т.",
    name3: "ЯККАСАРАЙСКИЙ р-н",
    name4: "Yakkasaroy district",
    parent_number: 14,
  },
  {
    number: 1405,
    name1: "Shayxontohur t.",
    name2: "Шайхонтохур т.",
    name3: "ШАЙХАНТАУРСКИЙ р-н",
    name4: "Shaikhontokhur district",
    parent_number: 14,
  },
  {
    number: 1406,
    name1: "Chilonzor t.",
    name2: "Чилонзор т.",
    name3: "ЧИЛАНЗАРСКИЙ р-н",
    name4: "Chilonzor district",
    parent_number: 14,
  },
  {
    number: 1407,
    name1: "Sergeli t.",
    name2: "Сергели т.",
    name3: "СЕРГЕЛИНСКИЙ р-н",
    name4: "Sergely district",
    parent_number: 14,
  },
  {
    number: 1408,
    name1: "Yashnobod t.",
    name2: "Яшнобод т.",
    name3: "ХАМЗИНСКИЙ р-н",
    name4: "Yashnabad district",
    parent_number: 14,
  },
  {
    number: 1409,
    name1: "Olmazor t.",
    name2: "Олмазор т.",
    name3: "АЛМАЗАРСКИЙ р-н",
    name4: "Almazor district",
    parent_number: 14,
  },
  {
    number: 1410,
    name1: "Uchtepa t.",
    name2: "Учтепа т.",
    name3: "УЧТЕПИНСКИЙ РАЙОН",
    name4: "Uchtep district",
    parent_number: 14,
  },
  {
    number: 1411,
    name1: "Bektemir t.",
    name2: "Бектемир т.",
    name3: "БЕКТЕМИРСКИЙ р-н",
    name4: "Bektemir district",
    parent_number: 14,
  },
  {
    number: 1412,
    name1: "Yangihayot t.",
    name2: "Янгиҳаёт т.",
    name3: "ЯНГИХАЙОТСКИЙ р-н",
    name4: "Yangihayat district",
    parent_number: 14,
  },
];
